# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eABjbN1NHzwhv-nXikDZr-IKTkW6FWLx
"""

i=0
print("Reading file content:")
try:

    with open('sample.txt', 'r') as file:

        for line in file:
            i=i+1
            print("Line",i,":",line.strip())
except FileNotFoundError:
    print("Error: The file 'sample.txt' does not exist.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")