# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eABjbN1NHzwhv-nXikDZr-IKTkW6FWLx
"""

try:

  with open("output.txt", "w") as file:
    data = input("Enter text to write to the file: ")
    file.write(data + "\n")

    print("Data written to output.txt successfully.")

# Step 2: Append additional data
  with open("output.txt", "a") as file:
    additional_data = input("Enter text to append to the file: ")
    file.write(additional_data + "\n")

    print("Additional data appended successfully.")

# Step 3: Read and display the file content
  with open("output.txt", "r") as file:
    print("\nFinal content of output.txt:")
    print(file.read())
except FileNotFoundError:
    print("Error: The file 'sample.txt' does not exist.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")